-- Proactive alerts: one row per (officer, finding). Generated by the alert
-- engine (lib/alerts.ts) and fanned out to the officers whose scope the
-- finding falls in.
CREATE TABLE "Alert" (
    "id"         TEXT NOT NULL,
    "userId"     INTEGER NOT NULL,
    "kind"       TEXT NOT NULL,
    "severity"   TEXT NOT NULL DEFAULT 'info',
    "title"      TEXT NOT NULL,
    "detail"     TEXT NOT NULL,
    "query"      TEXT NOT NULL DEFAULT '',
    "districtId" INTEGER,
    "caseId"     INTEGER,
    "dedupeKey"  TEXT NOT NULL,
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "readAt"     TIMESTAMP(3),
    CONSTRAINT "Alert_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Alert_userId_dedupeKey_key" ON "Alert"("userId", "dedupeKey");
CREATE INDEX "Alert_userId_readAt_idx" ON "Alert"("userId", "readAt");
CREATE INDEX "Alert_userId_createdAt_idx" ON "Alert"("userId", "createdAt");

ALTER TABLE "Alert" ADD CONSTRAINT "Alert_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "KhabriUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- The scoped (non-owner) role reads its own alerts through the app, which
-- always filters by userId; no RLS policy needed, but the role must be able to
-- read the table at all.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'khabri_scoped') THEN
    GRANT SELECT, INSERT, UPDATE ON "Alert" TO khabri_scoped;
  END IF;
END $$;
